// SPDX-License-Identifier: MIT
//
// Wikipedia article → ordered sections.
//
// ZIM articles ship as HTML. Feeding a 400 KB blob to a small LLM
// wastes context and inflates KV-cache memory. Instead we parse the
// article's heading structure (`<h2>` / `<h3>`) once per article,
// split into self-contained sections, and let callers pull just the
// parts that answer the query.
//
// The parser is intentionally lightweight — regex over string
// boundaries, no DOM tree, no external dependency — because Wikipedia
// ZIMs are generated by Kiwix and carry a predictable, simple HTML
// shape (no JavaScript, no async fragments, no nested `<section>`
// wrappers we'd need a full parser to handle).

import Foundation

public struct ArticleSection: Sendable, Equatable {
    /// Heading text as it appears in the article, with any anchor
    /// markup stripped. The very first section — the lead — carries
    /// the title `""` so callers can distinguish it from named
    /// sections (which always have a non-empty title).
    public let title: String
    /// Heading level. 0 for the lead (pre-first-heading), 2 for an
    /// `<h2>`, 3 for `<h3>`. We don't go deeper than h3 — finer
    /// splits yield chunks too small to be useful for Q&A.
    public let level: Int
    /// Plain-text body (HTML tags stripped, entities decoded,
    /// whitespace collapsed).
    public let text: String
    /// Approximate byte size of the plain-text body — useful for
    /// pickling decisions (skip navigation-only sections).
    public var bytes: Int { text.utf8.count }

    public init(title: String, level: Int, text: String) {
        self.title = title
        self.level = level
        self.text = text
    }
}

public enum ArticleSections {

    /// Sections Kiwix-generated Wikipedia ZIMs typically have but
    /// which carry no useful prose for a Q&A model. Skipping them
    /// means the section list the model sees stays short and signal-
    /// dense. Matched case-insensitively against the heading text.
    private static let skippedTitles: Set<String> = [
        "see also",
        "references",
        "notes",
        "footnotes",
        "citations",
        "further reading",
        "external links",
        "bibliography",
        "sources",
    ]

    /// Parse an article HTML body into ordered sections. The first
    /// entry is always the lead (title `""`, level `0`). Empty-body
    /// sections and the known-boilerplate ones are dropped.
    public static func parse(html: String) -> [ArticleSection] {
        // Rough-and-ready: find each `<h2 …>…</h2>` / `<h3 …>…</h3>`
        // occurrence, record its heading text and start offset, then
        // slice the body between successive headings.
        let headingPattern = #"<h([23])\b[^>]*>(.*?)</h\1>"#
        guard let regex = try? NSRegularExpression(
            pattern: headingPattern, options: [.caseInsensitive, .dotMatchesLineSeparators]
        ) else {
            return [ArticleSection(title: "", level: 0, text: stripHTML(html))]
        }
        let fullRange = NSRange(html.startIndex..<html.endIndex, in: html)
        let matches = regex.matches(in: html, range: fullRange)

        struct Marker {
            let level: Int
            let title: String
            let headingStart: Int
            let headingEnd: Int
        }
        var markers: [Marker] = []
        for m in matches {
            guard let headingRange = Range(m.range, in: html),
                  let levelRange = Range(m.range(at: 1), in: html),
                  let titleRange = Range(m.range(at: 2), in: html)
            else { continue }
            let level = Int(html[levelRange]) ?? 2
            let title = stripHTML(String(html[titleRange]))
                .trimmingCharacters(in: .whitespacesAndNewlines)
            markers.append(Marker(
                level: level,
                title: title,
                headingStart: html.distance(from: html.startIndex, to: headingRange.lowerBound),
                headingEnd: html.distance(from: html.startIndex, to: headingRange.upperBound)
            ))
        }

        var sections: [ArticleSection] = []
        // Lead = everything before the first h2/h3.
        let leadEndOffset = markers.first?.headingStart ?? html.count
        let leadEndIdx = html.index(html.startIndex, offsetBy: leadEndOffset)
        let leadText = stripHTML(String(html[..<leadEndIdx]))
        if !leadText.isEmpty {
            sections.append(ArticleSection(title: "", level: 0, text: leadText))
        }
        // Named sections.
        for (i, marker) in markers.enumerated() {
            let bodyStartIdx = html.index(html.startIndex, offsetBy: marker.headingEnd)
            let nextHeadingStart = (i + 1 < markers.count)
                ? markers[i + 1].headingStart : html.count
            let bodyEndIdx = html.index(html.startIndex, offsetBy: nextHeadingStart)
            let raw = String(html[bodyStartIdx..<bodyEndIdx])
            let text = stripHTML(raw)
            if text.isEmpty { continue }
            if skippedTitles.contains(marker.title.lowercased()) { continue }
            sections.append(ArticleSection(
                title: marker.title, level: marker.level, text: text
            ))
        }
        return sections
    }

    /// Find a section whose title matches `query` (case-insensitive,
    /// prefix-tolerant). Used by `get_article_section` so callers
    /// can pass a human-friendly title from a prior
    /// `list_article_sections` response without worrying about
    /// exact whitespace / casing.
    public static func find(_ query: String, in sections: [ArticleSection]) -> ArticleSection? {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if q.isEmpty || q == "lead" || q == "summary" || q == "intro" {
            return sections.first
        }
        if let exact = sections.first(where: { $0.title.lowercased() == q }) {
            return exact
        }
        if let prefix = sections.first(where: { $0.title.lowercased().hasPrefix(q) }) {
            return prefix
        }
        return sections.first(where: { $0.title.lowercased().contains(q) })
    }

    // MARK: - HTML → text

    /// Strip HTML tags + decode the handful of entities we actually
    /// see in Kiwix Wikipedia output. Intentionally not a full HTML
    /// parser — the ZIM output is regular enough that this covers
    /// >99% of articles and is ~30× faster than pulling in SwiftSoup.
    public static func stripHTML(_ html: String) -> String {
        var out = html
        // Remove pronunciation + coordinate spans first, honouring nested
        // <span>s — Wikipedia wraps IPA in per-character spans, so the
        // crude non-greedy `removeBlock` can't be used. Kills the IPA glyph
        // cluster, the ⓘ "listen" button, and inline coordinate spans
        // before they reach TTS as symbol-by-symbol gibberish.
        out = removeSpansByClass(out, ["ipa", "rt-commentedtext", "ext-phonos", "geo", "coordinates"])
        // Drop known-noisy blocks whole, before tag-stripping, so
        // their inner text doesn't pollute prose.
        out = removeBlock(out, tag: "script")
        out = removeBlock(out, tag: "style")
        out = removeNestedBlock(out, tag: "table")   // infoboxes + nav/sidebar tables (nest!)
        out = removeNestedBlock(out, tag: "figure")  // pictures + captions
        out = removeBlock(out, tag: "nav")
        // mdwiki embeds short instructional clips via `<video>` tags
        // with nested `<source>` / `<track>` elements. Drop the whole
        // block so a path like `audio/foo.mp3` doesn't end up in the
        // prose the model reads aloud.
        out = removeBlock(out, tag: "video")
        out = removeBlock(out, tag: "audio")
        // Turn paragraph/list breaks into real whitespace so prose
        // doesn't mash together.
        let blockBreaks = ["</p>", "</li>", "</h2>", "</h3>", "</h4>", "</div>", "<br>", "<br/>", "<br />"]
        for b in blockBreaks { out = out.replacingOccurrences(of: b, with: "\n") }
        // Strip tags.
        out = out.replacingOccurrences(
            of: "<[^>]+>", with: " ", options: .regularExpression
        )
        // Decode the common entities. Full HTML entity decode is
        // overkill; this catches the ones Kiwix emits.
        let entities: [(String, String)] = [
            ("&nbsp;", " "), ("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">"),
            ("&quot;", "\""), ("&apos;", "'"), ("&#39;", "'"), ("&ndash;", "–"),
            ("&mdash;", "—"), ("&hellip;", "…"),
        ]
        for (k, v) in entities { out = out.replacingOccurrences(of: k, with: v) }
        // Strip pronunciation/coordinate artifacts that survive tag-
        // stripping (anything the span removal above didn't catch) and
        // tidy the parentheticals they empty out — see stripSpeechArtifacts.
        out = stripSpeechArtifacts(out)
        // Collapse whitespace.
        out = out.replacingOccurrences(
            of: "[ \\t]+", with: " ", options: .regularExpression
        )
        out = out.replacingOccurrences(
            of: " *\n *", with: "\n", options: .regularExpression
        )
        out = out.replacingOccurrences(
            of: "\n{3,}", with: "\n\n", options: .regularExpression
        )
        return out.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Remove `<tag>…</tag>` blocks (outermost pairs). Crude but fine
    /// for tags that never nest (script/style/nav/video/audio).
    private static func removeBlock(_ html: String, tag: String) -> String {
        let pattern = "<\(tag)\\b[^>]*>[\\s\\S]*?</\(tag)>"
        return html.replacingOccurrences(
            of: pattern,
            with: " ",
            options: [.regularExpression, .caseInsensitive]
        )
    }

    /// Depth-aware `<tag>…</tag>` removal for tags that NEST. The maxi
    /// builds nest tables three deep inside navbox/sidebar templates —
    /// the non-greedy `removeBlock` cut at the FIRST `</table>`, leaking
    /// the inner link farm into section prose (device capture
    /// 2026-07-02: a "gravitational waves" answer that was 2 kB of
    /// looping physicist names from the General-relativity sidebar).
    private static func removeNestedBlock(_ html: String, tag: String) -> String {
        let ns = html as NSString
        guard let re = try? NSRegularExpression(
            pattern: "<(/?)\(tag)\\b[^>]*>", options: [.caseInsensitive]
        ) else { return html }
        var out = ""
        var depth = 0
        var keptUpTo = 0
        for m in re.matches(in: html, range: NSRange(location: 0, length: ns.length)) {
            let isClose = ns.substring(with: m.range(at: 1)) == "/"
            if depth == 0 {
                if isClose { continue }   // stray close — generic strip gets it
                out += ns.substring(
                    with: NSRange(location: keptUpTo, length: m.range.location - keptUpTo))
                depth = 1
            } else {
                depth += isClose ? -1 : 1
                if depth == 0 {
                    out += " "
                    keptUpTo = m.range.location + m.range.length
                }
            }
        }
        if depth == 0 {
            out += ns.substring(from: keptUpTo)
        }
        // Unclosed outermost tag: everything after it was inside the
        // block — dropping it beats leaking a truncated link farm.
        return out
    }

    /// Remove `<span class="…">…</span>` blocks whose class has any token
    /// in `classTokens`, honouring nested `<span>`s. Wikipedia renders an
    /// IPA pronunciation as a per-character span tree wrapped in
    /// `rt-commentedText`, alongside an `ext-phonos` ⓘ button and inline
    /// `geo` coordinate spans — none removable by the non-greedy
    /// `removeBlock`. Token (not substring) match so "geo" doesn't also
    /// eat "geography".
    private static func removeSpansByClass(_ html: String, _ classTokens: Set<String>) -> String {
        let ns = html as NSString
        guard let re = try? NSRegularExpression(
            pattern: "<(/?)span\\b([^>]*)>", options: [.caseInsensitive])
        else { return html }
        let tags = re.matches(in: html, range: NSRange(location: 0, length: ns.length))
        var removals: [NSRange] = []
        var i = 0
        while i < tags.count {
            let open = tags[i]
            if open.range(at: 1).length > 0 { i += 1; continue }  // a </span>
            let attrs = ns.substring(with: open.range(at: 2)).lowercased()
            var hit = false
            if let r = attrs.range(of: "class=\""),
               let q = attrs[r.upperBound...].firstIndex(of: "\"") {
                for tok in attrs[r.upperBound..<q].split(whereSeparator: { $0 == " " || $0 == "\t" }) {
                    if classTokens.contains(String(tok)) { hit = true; break }
                }
            }
            if !hit { i += 1; continue }
            // Walk to the matching close, tracking nested span depth.
            var depth = 1, j = i + 1
            while j < tags.count {
                depth += (tags[j].range(at: 1).length > 0) ? -1 : 1
                if depth == 0 { break }
                j += 1
            }
            let endLoc = (j < tags.count) ? (tags[j].range.location + tags[j].range.length) : ns.length
            removals.append(NSRange(location: open.range.location, length: endLoc - open.range.location))
            i = j + 1
        }
        if removals.isEmpty { return html }
        let m = NSMutableString(string: html)
        for r in removals.reversed() { m.replaceCharacters(in: r, with: " ") }
        return m as String
    }

    /// Strip pronunciation/coordinate noise left in prose after tag-
    /// stripping — it reads as gibberish through TTS. Safe to run on any
    /// article text: slash/bracket IPA runs are unambiguous, and the
    /// parenthetical tidy only fires on the residue these removals leave.
    private static func stripSpeechArtifacts(_ text: String) -> String {
        // IPA / phonetic code points: IPA Extensions + spacing modifiers
        // (ˈ ˌ ː) + combining diacritics + phonetic extensions, plus the
        // Latin-1 vowels IPA reuses (æ ø œ).
        let ipa = "[\\x{0250}-\\x{02FF}\\x{0300}-\\x{036F}\\x{1D00}-\\x{1D7F}\\x{00E6}\\x{00F8}\\x{0153}]"
        var out = text.replacingOccurrences(of: "\u{24D8}", with: " ")  // ⓘ
        func rx(_ pattern: String, _ replacement: String, ci: Bool = false) {
            out = out.replacingOccurrences(
                of: pattern, with: replacement,
                options: ci ? [.regularExpression, .caseInsensitive] : [.regularExpression])
        }
        rx("\\(\\s*listen\\s*\\)", "", ci: true)            // "(listen)"
        rx("english pronunciation:?", "", ci: true)         // label
        rx("/[^/\\n]*\(ipa)[^/\\n]*/", "")                  // /ˈkæl…/ slash IPA
        rx("\\[[^\\]\\n]*\(ipa)[^\\]\\n]*\\]", "")           // [neˈβaða] foreign IPA
        rx("\\b\\p{L}+:\\s*(?=[);])", "")                   // dangling "Spanish:" before ) or ;
        rx("\\(\\s*[;,]\\s*", "(")                           // "( ; X" → "(X"
        rx("\\s*[;,]\\s*\\)", ")")                           // "X ; )" → "X)"
        rx("\\(\\s*\\)", "")                                 // "( )" → ∅
        return out
    }
}
