// SPDX-License-Identifier: MIT
//
// Wikipedia article → ordered sections.
//
// ZIM articles ship as HTML. Feeding a 400 KB blob to a small LLM
// wastes context and inflates KV-cache memory. Instead we parse the
// article's heading structure (`<h2>` / `<h3>`) once per article,
// split into self-contained sections, and let callers pull just the
// parts that answer the query.
//
// The parser is intentionally lightweight — regex over string
// boundaries, no DOM tree, no external dependency — because Wikipedia
// ZIMs are generated by Kiwix and carry a predictable, simple HTML
// shape (no JavaScript, no async fragments, no nested `<section>`
// wrappers we'd need a full parser to handle).

import Foundation

public struct ArticleSection: Sendable, Equatable {
    /// Heading text as it appears in the article, with any anchor
    /// markup stripped. The very first section — the lead — carries
    /// the title `""` so callers can distinguish it from named
    /// sections (which always have a non-empty title).
    public let title: String
    /// Heading level. 0 for the lead (pre-first-heading), 2 for an
    /// `<h2>`, 3 for `<h3>`. We don't go deeper than h3 — finer
    /// splits yield chunks too small to be useful for Q&A.
    public let level: Int
    /// Plain-text body (HTML tags stripped, entities decoded,
    /// whitespace collapsed).
    public let text: String
    /// Approximate byte size of the plain-text body — useful for
    /// pickling decisions (skip navigation-only sections).
    public var bytes: Int { text.utf8.count }

    public init(title: String, level: Int, text: String) {
        self.title = title
        self.level = level
        self.text = text
    }
}

public enum ArticleSections {

    /// Sections Kiwix-generated Wikipedia ZIMs typically have but
    /// which carry no useful prose for a Q&A model. Skipping them
    /// means the section list the model sees stays short and signal-
    /// dense. Matched case-insensitively against the heading text.
    private static let skippedTitles: Set<String> = [
        "see also",
        "references",
        "notes",
        "footnotes",
        "citations",
        "further reading",
        "external links",
        "bibliography",
        "sources",
    ]

    /// Parse an article HTML body into ordered sections. The first
    /// entry is always the lead (title `""`, level `0`). Empty-body
    /// sections and the known-boilerplate ones are dropped.
    public static func parse(html: String) -> [ArticleSection] {
        // Rough-and-ready: find each `<h2 …>…</h2>` / `<h3 …>…</h3>`
        // occurrence, record its heading text and start offset, then
        // slice the body between successive headings.
        let headingPattern = #"<h([23])\b[^>]*>(.*?)</h\1>"#
        guard let regex = try? NSRegularExpression(
            pattern: headingPattern, options: [.caseInsensitive, .dotMatchesLineSeparators]
        ) else {
            return [ArticleSection(title: "", level: 0, text: stripHTML(html))]
        }
        let fullRange = NSRange(html.startIndex..<html.endIndex, in: html)
        let matches = regex.matches(in: html, range: fullRange)

        struct Marker {
            let level: Int
            let title: String
            let headingStart: Int
            let headingEnd: Int
        }
        var markers: [Marker] = []
        for m in matches {
            guard let headingRange = Range(m.range, in: html),
                  let levelRange = Range(m.range(at: 1), in: html),
                  let titleRange = Range(m.range(at: 2), in: html)
            else { continue }
            let level = Int(html[levelRange]) ?? 2
            let title = stripHTML(String(html[titleRange]))
                .trimmingCharacters(in: .whitespacesAndNewlines)
            markers.append(Marker(
                level: level,
                title: title,
                headingStart: html.distance(from: html.startIndex, to: headingRange.lowerBound),
                headingEnd: html.distance(from: html.startIndex, to: headingRange.upperBound)
            ))
        }

        var sections: [ArticleSection] = []
        // Lead = everything before the first h2/h3.
        let leadEndOffset = markers.first?.headingStart ?? html.count
        let leadEndIdx = html.index(html.startIndex, offsetBy: leadEndOffset)
        let leadText = stripHTML(String(html[..<leadEndIdx]))
        if !leadText.isEmpty {
            sections.append(ArticleSection(title: "", level: 0, text: leadText))
        }
        // Named sections.
        for (i, marker) in markers.enumerated() {
            let bodyStartIdx = html.index(html.startIndex, offsetBy: marker.headingEnd)
            let nextHeadingStart = (i + 1 < markers.count)
                ? markers[i + 1].headingStart : html.count
            let bodyEndIdx = html.index(html.startIndex, offsetBy: nextHeadingStart)
            let raw = String(html[bodyStartIdx..<bodyEndIdx])
            let text = stripHTML(raw)
            if text.isEmpty { continue }
            if skippedTitles.contains(marker.title.lowercased()) { continue }
            sections.append(ArticleSection(
                title: marker.title, level: marker.level, text: text
            ))
        }
        return sections
    }

    /// Find a section whose title matches `query` (case-insensitive,
    /// prefix-tolerant). Used by `get_article_section` so callers
    /// can pass a human-friendly title from a prior
    /// `list_article_sections` response without worrying about
    /// exact whitespace / casing.
    public static func find(_ query: String, in sections: [ArticleSection]) -> ArticleSection? {
        let q = query.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        if q.isEmpty || q == "lead" || q == "summary" || q == "intro" {
            return sections.first
        }
        if let exact = sections.first(where: { $0.title.lowercased() == q }) {
            return exact
        }
        if let prefix = sections.first(where: { $0.title.lowercased().hasPrefix(q) }) {
            return prefix
        }
        return sections.first(where: { $0.title.lowercased().contains(q) })
    }

    // MARK: - HTML → text

    /// Strip HTML tags + decode the handful of entities we actually
    /// see in Kiwix Wikipedia output. Intentionally not a full HTML
    /// parser — the ZIM output is regular enough that this covers
    /// >99% of articles and is ~30× faster than pulling in SwiftSoup.
    static func stripHTML(_ html: String) -> String {
        var out = html
        // Drop known-noisy blocks whole, before tag-stripping, so
        // their inner text doesn't pollute prose.
        out = removeBlock(out, tag: "script")
        out = removeBlock(out, tag: "style")
        out = removeBlock(out, tag: "table")   // infoboxes + nav tables
        out = removeBlock(out, tag: "figure")  // pictures + captions
        out = removeBlock(out, tag: "nav")
        // Turn paragraph/list breaks into real whitespace so prose
        // doesn't mash together.
        let blockBreaks = ["</p>", "</li>", "</h2>", "</h3>", "</h4>", "</div>", "<br>", "<br/>", "<br />"]
        for b in blockBreaks { out = out.replacingOccurrences(of: b, with: "\n") }
        // Strip tags.
        out = out.replacingOccurrences(
            of: "<[^>]+>", with: " ", options: .regularExpression
        )
        // Decode the common entities. Full HTML entity decode is
        // overkill; this catches the ones Kiwix emits.
        let entities: [(String, String)] = [
            ("&nbsp;", " "), ("&amp;", "&"), ("&lt;", "<"), ("&gt;", ">"),
            ("&quot;", "\""), ("&apos;", "'"), ("&#39;", "'"), ("&ndash;", "–"),
            ("&mdash;", "—"), ("&hellip;", "…"),
        ]
        for (k, v) in entities { out = out.replacingOccurrences(of: k, with: v) }
        // Collapse whitespace.
        out = out.replacingOccurrences(
            of: "[ \\t]+", with: " ", options: .regularExpression
        )
        out = out.replacingOccurrences(
            of: " *\n *", with: "\n", options: .regularExpression
        )
        out = out.replacingOccurrences(
            of: "\n{3,}", with: "\n\n", options: .regularExpression
        )
        return out.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    /// Remove `<tag>…</tag>` blocks (outermost pairs). Crude but
    /// matches the HTML Kiwix emits — no deeply-nested tables.
    private static func removeBlock(_ html: String, tag: String) -> String {
        let pattern = "<\(tag)\\b[^>]*>[\\s\\S]*?</\(tag)>"
        return html.replacingOccurrences(
            of: pattern,
            with: " ",
            options: [.regularExpression, .caseInsensitive]
        )
    }
}
